name = "book-orders"
main = "src/index.js"

compatibility_date = "2026-05-12"

workers_dev = false

# =========================================================
# 🚀 PRODUCTION
# =========================================================
[env.production]
name = "book-orders"

routes = [
  { pattern = "api.fundorashop.com/*", zone_name = "fundorashop.com" }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "app-db"
database_id = "3b2d0500-0527-425a-a0cb-bc92e4fa51b8"

[[env.production.kv_namespaces]]
binding = "ORDER_RATE_LIMIT"
id = "764239cfab034e5eacda3e8278f38c55"

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "f3d5caade25442859944e5e2cced3a0a"


# =========================================================
# 🧪 STAGING
# =========================================================
[env.staging]
name = "book-orders-staging"

workers_dev = false

routes = [
  { pattern = "staging-api.fundorashop.com/*", zone_name = "fundorashop.com" }
]

[[env.staging.d1_databases]]
binding = "DB"
database_name = "app-db-staging"
database_id = "c1dab80d-e183-4c7b-a6ec-bd45a9e559ae"

[[env.staging.kv_namespaces]]
binding = "ORDER_RATE_LIMIT"
id = "2c8be46544ba4adca0da901b3b54979a"

[[env.staging.kv_namespaces]]
binding = "SESSIONS"
id = "3516be74327c4493af038730de5bbd84"


# Enable logs for debugging
[observability]
enabled = true