name = "book-orders"
main = "src/index.js"
compatibility_date = "2026-05-12"
workers_dev = true

# =========================================================
# 🚀 PRODUCTION
# =========================================================

routes = [
  { pattern = "api.fundorashop.com/*", zone_name = "fundorashop.com" },
  { pattern = "api.fundorashop.com/v1/*", zone_name = "fundorashop.com" }
]

[[d1_databases]]
binding = "DB"
database_name = "app-db"
database_id = "3b2d0500-0527-425a-a0cb-bc92e4fa51b8"

[[kv_namespaces]]
binding = "ORDER_RATE_LIMIT"
id = "ea7782379a6e4b4e9687d001478606ac"

[[kv_namespaces]]
binding = "SESSIONS"
id = "f3d5caade25442859944e5e2cced3a0a"

# =========================================================
# 🚀 STAGING
# =========================================================

[env.staging]
name = "book-orders-staging"
workers_dev = true

routes = [
  { pattern = "staging-api.fundorashop.com/*", zone_name = "fundorashop.com" }
]

[[env.staging.d1_databases]]
binding = "DB"
database_name = "app-db-staging"
database_id = "c1dab80d-e183-4c7b-a6ec-bd45a9e559ae"

[[env.staging.kv_namespaces]]
binding = "ORDER_RATE_LIMIT"
id = "ea7782379a6e4b4e9687d001478606ac"

[[env.staging.kv_namespaces]]
binding = "SESSIONS"
id = "f3d5caade25442859944e5e2cced3a0a"